apiVersion: v1
kind: ReplicationController
metadata: 
 name: my-first-rc
spec:
 replicas: 3
 selector: 
  app: mynginx
  version: 2.3.7
 template:
   metadata:
    labels:
     app: mynginx
     version: 2.3.7
   spec:
    containers:
    - name: my-first-container
      image: maha4iac/myjavaaplication:2
      ports:
        - containerPort: 8080