apiVersion: v1
kind: Service
metadata:
 name: mysvc
 labels: 
  app: mynginx
  version: 2.3.6
spec:
 type: NodePort
 ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
 selector:
  app: mynginx 
  version: 2.3.6

  